### ISSUE TITLE
The first leter of the path / directory is removed

### ISSUE THREAD

**Issue by codinglogicinc** [Lymphatus/caesium-clt#19]
say you have files under /home/ubuntu/imagetests/unoptimized/
and you want to output files to /home/ubuntu/imagetests/optimized/

 /home/ubuntu/imagetests/unoptimized/Ch1/image1.jpg becomes  /home/ubuntu/imagetests/optimized/h1/image1.jpg

 /home/ubuntu/imagetests/unoptimized/Ch1/image2.jpg becomes  /home/ubuntu/imagetests/optimized/h1/image2.jpg
ext.
included is a modified helper.c file that fixes the problem.

[helper.zip](https://github.com/Lymphatus/caesium-clt/files/1460965/helper.zip)

**Comment by Lymphatus** [comment]
It is indeed a bug but it's indirectly been addressed in #17 .
Thanks for you submission tho!
