### ISSUE TITLE
Problems with Similar Folder Names for output and input folder

### ISSUE THREAD

**Issue by VanKusanagi** [Lymphatus/caesium-clt#23]
Hi,

I have noticed that when I input the Output Folder with a name that starts eactly as my input folder, the compression throws the error "[ERROR] 12: Cannot set output folder inside the input one
". 
I have attached a screenshot showing just that
![image](https://user-images.githubusercontent.com/13829905/34432316-394e3c9c-ec9c-11e7-8704-ff8b3f98663a.png)

But once you change the name slightly, it all works fine

**Comment by Lymphatus** [comment]
This is already being addressed in the 0.11.0 branch, which will be merged into master soon.
Thanks for reporting.
