### ISSUE TITLE
Using -o does place output into root (/) in Linux

### ISSUE THREAD

**Issue by bardiir** [Lymphatus/caesium-clt#26]
```
/caesium # caesiumclt -o /tmp ./toll.jpg 
(1/1) toll.jpg -> /toll.jpg
1.23 MB -> 1.23 MB [-0.20%]
-------------------------------
Compression completed in 0m0s82ms
1.23 MB -> 1.23 MB [-0.20% | -2.47 KB]
```

Previous versions did place the image to /tmp/toll.jpg then. The current version doesn't do this.

**Comment by Lymphatus** [comment]
I'm gonna look into this as soon as possible.

Thanks for the report.

**Comment by Sergi0O** [comment]
That is exactly the same issue that I have

**Comment by Lymphatus** [comment]
On my working machine running OS X 10.13.1 I cannot reproduce the issue. I guess this is a problem on Linux (maybe Windows, I've not tested yet). I'm gonna test on a Arch, Ubuntu and Debian machine as soon as possible.

**Comment by Lymphatus** [comment]
I can confirm this is an issue, at least on Ubuntu. Working on a fix.
