### ISSUE TITLE
is this the most active/maintained version of caesium?

### ISSUE THREAD

**Issue by WPFilmmaker** [Lymphatus/caesium-clt#28]
I am a linux user and used caesium with Wine, but today I found caesium-clt, I was wondering is this the most maintained version?The other one seems to be stalled. Thanks for the clarification

**Comment by Lymphatus** [comment]
Hi,

Yes, kind of. This is the most updated version along with [libcaesium](https://github.com/Lymphatus/libcaesium). Just note this is command line and still beta, so has some issues still.

**Comment by WPFilmmaker** [comment]
@Lymphatus  Thanks! No problem, I am used to terminal, I will test it and report any bugs/feedbacks I have for my distro (ubuntu).

**Comment by Lymphatus** [comment]
Thank you! Please note that the current version has some (critical) issues with Linux, Ubuntu in particular. Take a look at the other open issues to have an idea of them.

I'm closing this. If you have any other problem or question, just open another thread.
Thanks again.
