### ISSUE TITLE
Caesium-clt installs fine but gives "command not found"

### ISSUE THREAD

**Issue by WPFilmmaker** [Lymphatus/caesium-clt#29]
stuff@stuff-VirtualBox:~$ cd /home/stuff/Downloads/caesium-clt-0.10.2-beta

stuff@stuff-VirtualBox:~/Downloads/caesium-clt-0.10.2-beta$ mkdir build && cd build

stuff@stuff-VirtualBox:~/Downloads/caesium-clt-0.10.2-beta/build$ cmake ..
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/stuff/Downloads/caesium-clt-0.10.2-beta/build

stuff@stuff-VirtualBox:/Downloads/caesium-clt-0.10.2-beta/build$ make
Scanning dependencies of target caesiumclt
[ 16%] Building C object src/CMakeFiles/caesiumclt.dir/helper.c.o
[ 33%] Building C object src/CMakeFiles/caesiumclt.dir/error.c.o
[ 50%] Building C object src/CMakeFiles/caesiumclt.dir/optparse.c.o
[ 66%] Building C object src/CMakeFiles/caesiumclt.dir/main.c.o
[ 83%] Building C object src/CMakeFiles/caesiumclt.dir/utils.c.o
[100%] Linking C executable caesiumclt
[100%] Built target caesiumclt

stuff@stuff-VirtualBox:/Downloads/caesium-clt-0.10.2-beta/build$ sudo make install
[sudo] password for stuff:
[100%] Built target caesiumclt
Install the project...
-- Install configuration: ""
-- Installing: /usr/local/bin/caesiumclt

stuff@stuff-VirtualBox:/Downloads/caesium-clt-0.10.2-beta/build$ caesiumclt -v
0.10.2

stuff@stuff-VirtualBox:/Downloads/caesium-clt-0.10.2-beta/build$ caesium
caesium: command not found

**Any idea?**

**Comment by Lymphatus** [comment]
The right command to execute is `caesiumclt`, as you entered before on the line:
`stuff@stuff-VirtualBox:/Downloads/caesium-clt-0.10.2-beta/build$ caesiumclt -v`

**Comment by WPFilmmaker** [comment]
@Lymphatus Thanks! it worked, seems I just had to restart the OS :)
