### ISSUE TITLE
provide an easy way to install?

### ISSUE THREAD

**Issue by WPFilmmaker** [Lymphatus/caesium-clt#35]
Like flat pack? You could then add it to https://flathub.org/home to have more visibility?

**Comment by VivekanandSaraswati** [comment]
Hi @WPFilmmaker ,

You can install it on CENTOS by following steps. I install it on own CENTOS 7 of AWS:

Run following command to install
`$sudo yum install libtool autoconf git nasm pkg-config cmake mesa-libGLU exiv2 gcc-c++
$wget https://github.com/Lymphatus/caesium-clt/archive/0.12.1-beta.tar.gz
$tar -xvf 0.12.1-beta.tar.gz
$cd caesium-clt-0.12.1-beta
$sudo sh install.sh
$ mkdir build && cd build
$ cmake ..
$ make
$ sudo make install
$caesiumclt -v`

First command will install necessary software, 2nd command will download source file, 3rd command will extract source file, 4th command will goto extracted dir, 5th command will install libcaesium, 6th command will create build dir and goto build dir, and rest command will install software and add it into path.

**Comment by VivekanandSaraswati** [comment]
Hi @WPFilmmaker,

You can install it on Ubuntu 14.04.2 by following steps:

```
$sudo apt  install libtool autoconf git nasm pkg-config cmake  exiv2
$wget https://github.com/Lymphatus/caesium-clt/archive/0.12.1-beta.tar.gz
$tar -xvf 0.12.1-beta.tar.gz
$cd caesium-clt-0.12.1-beta
$sudo sh install.sh
$ mkdir build && cd build
$ cmake ..
$ make
$ sudo make install
$caesiumclt -v

```

**Comment by drosendo** [comment]
Issue on trying to install on mac.

`$ make
[ 16%] Building C object src/CMakeFiles/caesiumclt.dir/error.c.o
/Applications/caesium-clt/src/error.c:19:10: fatal error: 'caesium.h' file not found
#include <caesium.h>
         ^~~~~~~~~~~
1 error generated.
make[2]: *** [src/CMakeFiles/caesiumclt.dir/error.c.o] Error 1
make[1]: *** [src/CMakeFiles/caesiumclt.dir/all] Error 2
make: *** [all] Error 2
Mac-mini-de-WebDS:build WebDSmini$ make
[ 16%] Building C object src/CMakeFiles/caesiumclt.dir/error.c.o
/Applications/caesium-clt/src/error.c:19:10: fatal error: 'caesium.h' file not found
#include <caesium.h>
         ^~~~~~~~~~~
1 error generated.
make[2]: *** [src/CMakeFiles/caesiumclt.dir/error.c.o] Error 1
make[1]: *** [src/CMakeFiles/caesiumclt.dir/all] Error 2
make: *** [all] Error 2
`

**Comment by Lymphatus** [comment]
Did you install [libcaesium](https://github.com/Lymphatus/libcaesium)?

**Comment by drosendo** [comment]
Hi @Lymphatus,

Initially no but then I tried but I run into similar problem instaling it, there is always a file missing

**Comment by Lymphatus** [comment]
It's the same error even with the library installed or it's different?

**Comment by drosendo** [comment]
Hi,
It was a different error it was missing other files... but hey I went another way... hope you can fix it, it looked promising.

**Comment by Lymphatus** [comment]
I'm gonna look into it. I have a Mac and had no issues so fare, but I'll do some deeper testing.
