### ISSUE TITLE
Problem while installation

### ISSUE THREAD

**Issue by rakeshkasinathan** [Lymphatus/caesium-clt#36]
**While installing the caesiumclt following issue occured.
 /var/www/html/test/image_processing/caesium-clt/build$ make
[ 16%] Building C object src/CMakeFiles/caesiumclt.dir/error.c.o
/var/www/html/test/image_processing/caesium-clt/src/error.c:19:21: fatal error: caesium.h: No such file or directory
compilation terminated.
src/CMakeFiles/caesiumclt.dir/build.make:86: recipe for target 'src/CMakeFiles/caesiumclt.dir/error.c.o' failed
make[2]: *** [src/CMakeFiles/caesiumclt.dir/error.c.o] Error 1
CMakeFiles/Makefile2:85: recipe for target 'src/CMakeFiles/caesiumclt.dir/all' failed
make[1]: *** [src/CMakeFiles/caesiumclt.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Lymphatus** [comment]
I think you should install [libcaesium](https://github.com/Lymphatus/libcaesium) first.
