### ISSUE TITLE
[ERROR] 203: Unrecognized error. after 1021 images

### ISSUE THREAD

**Issue by alexanderwilkinson** [Lymphatus/caesium-clt#38]
Just installed Caesium on Ubuntu 19.04 running on a server.  It performs fantastically, but crashes after 1021 images no matter which images it is given with error 203. Unrecognized error.  

I used the following command caesiumclt -q 30 -o ~/compressimages/ /home/MasterImages 

The code seems to process images non-sequentially, so I can't simply point it to the remaining images in an efficient way.   

This issue appears different to https://github.com/Lymphatus/caesium-clt/issues/27 

Has anyone encountered anything similar?

**Comment by Lymphatus** [comment]
Hi,

can you please me provide the parameters you used for the compression? If they matter in any way. I will run some tests.

**Comment by alexanderwilkinson** [comment]
Hi, 

 

I used caesiumclt -q 30 -o ~/compressimages/ /home/MasterImages 

 

The issue seems vaguely similar to https://github.com/Lymphatus/caesium-clt/issues/18 except the code failed for me on Ubuntu (rather than Windows), after 1020 images rather than 509, and with a slightly different error code.   

 

I eventually got everything to run using Docker - updating the docker file @  https://github.com/bardiir/caesium   (updated dockerfile at https://github.com/bardiir/caesium/issues/1 ) 

 

Amazingly useful code – 200,000 images compressed well in a very short period of time!

**Comment by Lymphatus** [comment]
I was able to reproduce the exact same issue on a Ubuntu 19.04 VM. I'm gonna have a look into it.

**Comment by Lymphatus** [comment]
The bug was coming from [libcaesium](https://github.com/Lymphatus/libcaesium) because the library could not close the opened files for compression. The opened files limit for the caesiumclt process was around ~1021, thus the error.

It was solved at Lymphatus/libcaesium@0a4bf12dea087dc56ff273f5087ad8a504420ca3.
