### ISSUE TITLE
Cannot run "caesiumclt -v" due to missing library

### ISSUE THREAD

**Issue by Kowa92** [Lymphatus/caesium-clt#44]
Hello,

i have a question for you. When i run `caesiumclt -v` from Terminal it says: 

`pi@raspberry:~ $ caesiumclt -v
caesiumclt: error while loading shared libraries: libcaesium.so: cannot open shared object file: No such file or directory
`

I have already compiled and installed the `libcaesium` library on my system. It is located at:

`
-- Installing: /usr/local/lib/libcaesium.so
-- Set runtime path of "/usr/local/lib/libcaesium.so" to "/opt/mozjpeg/lib"
`

The question is:

- Which should be the correct directory of this `libcaesium.so` missing library that the `caesiumclt -v` command looks for, once you launch it?

Thanks

**Comment by Lymphatus** [comment]
Hi,

on Unix systems the installer looks in `/usr/lib` by default. There's no option to change that by passing a variable (there should be, my bad), but a symlink should work.

**Comment by Kowa92** [comment]
> Hi,
> 
> on Unix systems the installer looks in `/usr/lib` by default. There's no option to change that by passing a variable (there should be, my bad), but a symlink should work.

Yea! Now it works. I fixed it by creating a symbolic link inside `/usr/lib` directory named `libcaesium.so` that points directly to `/usr/local/lib/libcaesium.so`.

Thank you very much!
