### ISSUE TITLE
Running make command in local failing

### ISSUE THREAD

**Issue by ykhandelwal913** [Lymphatus/caesium-clt#49]
make
[ 14%] Building C object src/CMakeFiles/caesiumclt.dir/vendor/optparse.c.o
[ 28%] Building C object src/CMakeFiles/caesiumclt.dir/error.c.o
[ 42%] Building C object src/CMakeFiles/caesiumclt.dir/helper.c.o
[ 57%] Building C object src/CMakeFiles/caesiumclt.dir/main.c.o
[ 71%] Building C object src/CMakeFiles/caesiumclt.dir/shared.c.o
[ 85%] Building C object src/CMakeFiles/caesiumclt.dir/utils.c.o
[100%] Linking C executable caesiumclt
ld: library not found for -lcaesium
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/caesiumclt] Error 1
make[1]: *** [src/CMakeFiles/caesiumclt.dir/all] Error 2
make: *** [all] Error 2
test:build test$ make -v
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0

I am trying to build it in monterey mac machine.

**Comment by Lymphatus** [comment]
Similar to #48, you need [libcaesium](https://github.com/Lymphatus/libcaesium) compiled on your machine. Look at the linked issue for details.
