### ISSUE TITLE
[WARNING] File ... was not compressed. Reason: Unknown (Code: 210)

### ISSUE THREAD

**Issue by nocte1337** [Lymphatus/caesium-clt#57]
Hi I just installed on ubuntu 22.04, cargo 1.68.0 using `cargo build --release`

Any file I trow at it, it gives me this error

```
[WARNING] File /home/test/htdocs/wp-content/uploads/2021/07/fashion-designer-template-hero-img-bg.jpg was not compressed. Reason: Unknown (Code: 210)
[WARNING] File /home/test/htdocs/wp-content/uploads/woocommerce-placeholder-300x300.png was not compressed. Reason: Unknown (Code: 210)
[WARNING] File /home/test/htdocs/wp-content/uploads/2021/07/fashion-designer-template-product-img-6.jpg was not compressed. Reason: Unknown (Code: 210)
```

im using this command:
`test@server: ~/caesium-clt-main/target/release$ ./caesiumclt -q 90 -O -R -S -d -o /home/test/htdocs/wp-content/uploads /home/test/htdocs/wp-content/uploads`

**Comment by Lymphatus** [comment]
Might be something with folder permissions?

**Comment by Lymphatus** [comment]
Can you upload here some of the pictures that are failing? I might be able to reproduce the issue and eventually fix it.

**Comment by nocte1337** [comment]
![fashion-designer-template-hero-img-bg](https://user-images.githubusercontent.com/38387234/226343990-0d4d1d14-0fc2-40d6-b9ac-2aef54a254e2.jpg)
![woocommerce-placeholder](https://user-images.githubusercontent.com/38387234/226344070-746d011c-658f-4911-bb25-8c6a2e459501.png)
![fashion-designer-template-product-img-6](https://user-images.githubusercontent.com/38387234/226344120-c578f0d9-fd3c-49b6-8dc0-e9984bd3584a.jpg)

I don't think it depends on the files, I tried executing it on the whole website dir and got hundreds of warnings and no image was optimized

**Comment by Lymphatus** [comment]
It has to do with the `-d` option, which starts the program in dry run. If you remove it, the compression should be fine, although - of course - it will actually compress the files. Note that the option `-O` without arguments will overwrite all files, even if the output is bigger than the original, which is a common scenario with `-q 90`. You might want to specify `-O Bigger` to prevent overwriting smaller files.
