### ISSUE TITLE
Feature Request: Additional Options for specifying output width / height

### ISSUE THREAD

**Issue by lukasbindreiter** [Lymphatus/caesium-clt#58]
Hi,

I'm using `caesiumclt` to compress my image library, and it works great so far.

But since my phone camera (and I guess nowadays most phones do) takes really large pictures (~5000x3000 resolution) I'd like to reduce this a little bit as well.

Currently, It is possible to specify something like `--width 3000` and the height will be kept in the same aspect ratio, which works great for landscape photos, but not on portrait photos.

So an option to specify either the width or the height (chosen by the larger dimension) would be awesome, or maybe something like:
`--max-width 3000 --max-height 3000` could work to achieve this?

Also, in my library I also have some older photos which are at a lower resolution and which I then don't want to upscale to a `3000` pixel width. Would it be possible to add something like a `--no-upscaling` flag or so as well? Or if the `--max-width` / `--max-height` parameter from above were to be included it could become unnecessary I guess, that would be great as well.

My current workflow, which works but is basically a hack around this limitation just divides my library first into three separate folders:
- landscape
- portrait
- small photos that won't be resized

I then run `caesiumclt` on each of those, and afterwards combine the results again. But some more options like those specified above would make that workaround unnecessary.

Anyway thanks for an awesome tool and would love to hear additional thoughts on the feature ideas I described :smile:

**Comment by lukasbindreiter** [comment]
I just tested the GUI and I realized that a feature like this exists there in the Resize tab:

I belive setting it like this achieves exactly what I'm after:
![image](https://user-images.githubusercontent.com/21131639/228671010-0c14c22a-3f01-4d5c-9ea9-8887fc363e32.png)

So maybe allowing some sort of configuration in that style could work as well?

**Comment by Lymphatus** [comment]
A more advanced resize option could be a nice addition. I just want to point out that the GUI and the command line applications share the same compression engine underneath, but they are not 1 to 1 copy in terms of features. Usually the GUI has more options available.

**Comment by namtao** [comment]
![Screenshot 2024-08-06 204514](https://github.com/user-attachments/assets/8d7e8e23-ac35-4635-be17-6bbc44e87310)
I wonder if there is a Mode Size option like in the GUI? Thanks

**Comment by Lymphatus** [comment]
[Added](https://github.com/Lymphatus/caesium-clt/commit/e9ad78e4b41885cf80db41a6a3a7b73222f97e6f) options for `--long-edge` and `--short-edge` mirroring what the GUI version does.
For the no upscaling/max dimensions I'm still thinking how to approach the feature. Let you know.

**Comment by Lymphatus** [comment]
Released version 0.21.0 with `--long-edge` and `--short-edge` options.
