### ISSUE TITLE
caesiumclt.exe -R --overwrite deletes any non-image file

### ISSUE THREAD

**Issue by regorxxx** [Lymphatus/caesium-clt#69]
Using 
`caesiumclt.exe -R --overwrite all`
or
`caesiumclt.exe -R --overwrite bigger`

Any non-image file, which in fact throws an error, is nuked. This is a non-desired behavior and really dangerous, specially since you allow recursion.

Either allow a mask input to filter files to process (which should default to compatible images) or just process only compatible images.

**Comment by Lymphatus** [comment]
It should only replace files if they are correctly processed and should already skip files that are not supported. I tried a few commands and I was unable to reproduce the issue you are mentioning.
Can you provide a minimal example to reproduce? Likely the command you are executing and the folder/files structure you are compressing against. I'll fix it as soon as I'm able to reproduce it.

**Comment by regorxxx** [comment]
```
@echo off
caesiumclt.exe -R -S -q 95 --exif --overwrite bigger --output %1 %1
```

![image](https://github.com/Lymphatus/caesium-clt/assets/83307074/183ca84c-91e8-4be8-b737-141180998eca)
Before:
![image](https://github.com/Lymphatus/caesium-clt/assets/83307074/eb900bfa-ff98-450a-b317-e670e8b70d28)
After:
![image](https://github.com/Lymphatus/caesium-clt/assets/83307074/22ec4050-d502-44a5-84b2-a1dd8d53b83d)

In my test, the .txt files are nuked.

**Comment by Lymphatus** [comment]
Looking at the screenshot it seems you have an older version of the software. Which version are you using?

**Comment by regorxxx** [comment]
You are right, I was using 0.15.1. Seeing your changelog, it seems something was fixed with  -RS args, it may be this.

I was going to compile the newest version, but seeing I have to install 10GB of VS to build... maybe some other day.

**Comment by Lymphatus** [comment]
I think the `x86_64-pc-windows-gnu` Rust target it's way smaller in size. I don't remember if it actually requires VS but you might wanna give it a try.
