### ISSUE TITLE
How to specify optimization level for lossless PNG compression?

### ISSUE THREAD

**Issue by stamminator** [Lymphatus/caesium-clt#73]
The documentation for the `-q, --quality <quality>` argument states "sets output file quality between [0-100], 0 for optimization". It's not clear to me how the optimization level for PNG compression can be specified.

For example, what would be the arguments needed for the following 4 scenarios?

1. Lossy compress img.png using quality level 0
2. Lossy compress img.png using quality level 100
3. Losslessly compress img.png using optimization level 0
4. Losslessly compress img.png using optimization level 6

**Comment by stamminator** [comment]
@Lymphatus Roger that, thanks. In the meantime, does `-q 0` use lossless compression at some default optimization level?

**Comment by Lymphatus** [comment]
Defaults to 3, on a scale from 0 to 7. Internally sets the optimization preset of oxipng, which is used for optimization. [More info here](https://github.com/shssoichiro/oxipng?tab=readme-ov-file#usage) if interested.

**Comment by Lymphatus** [comment]
Released version 0.21.0 with the `--png-opt-level` to specify the level.

**Comment by stamminator** [comment]
Works like a charm, thanks!

![ZzD8pU9UHm](https://github.com/user-attachments/assets/8bbc2b29-93ec-4449-bba1-fba472a0bf4d)
